"""Built-in fallback selector map used when mcp-selectors/locators.json is missing/empty.

base_page.BasePage prefers locators.json but falls back to LOCATORS here so the
framework remains runnable even if the JSON file is reset between sessions.
"""

from __future__ import annotations

LOCATORS: dict[str, dict[str, list[str]]] = {
    "common": {
        "show_more_banner": [
            "a:has-text('Show more')",
            "text=Show more",
        ],
        "cookie_accept": [
            "button#onetrust-accept-btn-handler",
            "button[title='Accept All Cookies']",
            "button[aria-label*='Accept All' i]",
            "button:has-text('Accept All Cookies')",
            "button:has-text('Accept All')",
            "button:has-text('Allow All')",
        ],
    },
    "home": {
        "sign_in_link": [
            "a.signModal[aria-label='Login to your account']",
            "header a.signModal",
            "a.signModal:has-text('Sign In')",
            "a.signModal:has-text('Educator Sign In')",
            "header a:has-text('Educator Sign In')",
            "header a:has-text('Sign In')",
            "a#myaccount",
            "a[role='button']:has-text('Sign In')",
            "a:has-text('Sign In')",
            "button:has-text('Sign In')",
        ],
        "search_textbox": [
            "header input[name='q'].search-field",
            "input[name='q'].search-field",
            "input[placeholder*='Search by Keyword' i]",
            "input[type='search']",
            "input[name='q']",
        ],
        "search_submit_button": [
            "header form[role='search'] svg[name='search-button']",
            "form[role='search'] svg[name='search-button']",
            "header button[aria-label='Search']",
            "header form[role='search'] button[type='submit']",
            "form[role='search'] button[type='submit']",
            "header button:has-text('Search')",
            "button[type='submit']:has-text('Search')",
        ],
        "cart_link": [
            "header a.minicart-link",
            "a.minicart-link",
            "header a[href*='/en/cart']",
            "a[href$='/en/cart']",
            "a[aria-label*='Cart' i]",
            "a:has-text('Cart')",
        ],
        "logged_in_account": [
            "a.user-logout",
            "span.user-firstname:has-text('Welcome,')",
            ".user-firstname",
            "header :text-matches('Welcome,', 'i')",
            "button:has-text('My Account')",
            "header button:has-text('Welcome')",
            "text=My Account",
            "text=Welcome,",
        ],
    },
    "signin_modal": {
        "dialog": [
            "form#loginForm",
            "#loginForm",
            "div[role='dialog']:has-text('Account Sign In')",
            "div[role='dialog']:has-text('Sign In')",
            ".modal:has-text('Sign In')",
        ],
        "email_input": [
            "form#loginForm input.lf_email",
            "form#loginForm input[name='loginEmail']",
            "form#loginForm input#login-form-email",
            "#loginForm input.lf_email",
            "#loginForm input[name='loginEmail']",
            "#loginForm input[type='email']",
            "input.lf_email:visible",
            "input#login-form-email",
            "input[name='loginEmail']:visible",
            "input[type='email']:visible",
        ],
        "password_input": [
            "form#loginForm input.lf_password",
            "form#loginForm input[name='loginPassword']",
            "form#loginForm input#login-form-password",
            "#loginForm input.lf_password",
            "#loginForm input[name='loginPassword']",
            "#loginForm input[type='password']",
            "input.lf_password:visible",
            "input#login-form-password",
            "input[name='loginPassword']:visible",
            "input[type='password']:visible",
        ],
        "submit_button": [
            "form#loginForm button.lf_submit",
            "form#loginForm button[type='submit']",
            "form#loginForm button:has-text('Sign In')",
            "form#loginForm button:has-text('Login')",
            "#loginForm button.lf_submit",
            "#loginForm button[type='submit']",
            "#loginForm button:has-text('Sign In')",
            "div[role='dialog'] button:has-text('Sign In')",
            "div[role='dialog'] button[type='submit']",
            ".modal button:has-text('Sign In')",
        ],
    },
    "search_results": {
        "product_tile": [
            "div.product-tile",
            "div[class*='product-tile']",
            "div[data-itemid]",
            "div.grid-tile",
            "div[class*='grid-tile']",
        ],
        "first_tile_name": [
            "div.product-tile .product-name a",
            "div.product-tile .product-name",
            "a.thumb-link[title]",
            "a[title]",
            "div.product-tile h2",
            "div.product-tile h3",
        ],
        "first_tile_price": [
            "div.product-tile .line-item-total-price-amount",
            "div.product-tile .price-value",
            "div.product-tile .product-pricing .price-value",
            "div.product-tile .product-sales-price .price-value",
            ".price-value",
        ],
        "first_tile_add_to_cart": [
            "button.add-to-cart:not(.donateToClass):not(.d-none)",
            "button.add-to-cart:not(.donateToClass)",
            "button.add-to-cart",
            "button:has-text('Add to Cart')",
        ],
        "added_confirmation": [
            "#addedProductwrapper",
            "text=/added to (your )?cart/i",
            "div[role='dialog']:has-text('added to')",
            ".add-to-cart-messages",
            "div.toast:has-text('added')",
        ],
    },
    "filters": {
        "filter_by_label": [
            "h3.filter-by-label",
            ".refinement-bar h3:has-text('FILTER BY')",
            ".refinement-bar :text-matches('Filter\\\\s*By:?', 'i')",
            ":text-matches('Filter\\\\s*By:?', 'i')",
        ],
        "refinement_card": [
            "div.card.refinement",
            ".refinement-bar .refinement",
        ],
        "refinement_header": [
            "div.card.refinement > div.card-header",
        ],
        "refinement_h4": [
            "div.card.refinement h4[aria-label]",
        ],
        "clear_all": [
            ".refinement-bar .secondary-bar button.reset",
            ".refinement-bar button.reset:has-text('Clear All')",
            ".refinement-bar button:has-text('Clear All')",
            "button.reset:has-text('Clear All')",
            "button:has-text('Clear All')",
            "a:has-text('Clear All')",
        ],
    },
    "checkout": {
        "page_heading": [
            "h1:has-text('Checkout')",
            "h1.page-title:has-text('Checkout')",
            "[data-page-type='checkout']",
            ".checkout-page-title",
        ],
        "subtotal_value": [
            ".order-summary .sub-total .grand-total-sum",
            ".order-summary .subtotal-amount",
            ".order-totals .sub-total .value",
            ".summary-row.subtotal .value",
            ".order-summary [class*='subtotal'] [class*='value']",
        ],
        "shipping_value": [
            ".order-summary .shipping-cost",
            ".order-summary .shipping-total .grand-total-sum",
            ".summary-row.shipping .value",
            ".order-summary [class*='shipping'] [class*='value']",
        ],
        "hst_value": [
            ".order-summary .tax-total",
            ".order-summary .hst-amount",
            ".summary-row.tax .value",
            ".order-summary [class*='tax'] [class*='value']",
        ],
        "total_value": [
            ".order-summary .grand-total .grand-total-sum",
            ".order-summary .order-total .grand-total-sum",
            ".summary-row.grand-total .value",
            ".order-summary [class*='grand-total'] [class*='value']",
        ],
        "checkout_or_quote_button": [
            "a:has-text('Checkout or Create Quote')",
            "button:has-text('Checkout or Create Quote')",
            "a.cart-checkout-btn",
            "a:has-text('Checkout')",
            "button:has-text('Checkout')",
            "a:has-text('Create Quote')",
        ],
        "payment_or_quote_button": [
            "a:has-text('Payment or Create Quote')",
            "button:has-text('Payment or Create Quote')",
            "a.checkout-continue-btn",
            "a.btn-primary:has-text('Payment')",
            "a.btn-primary:has-text('Create Quote')",
            "a:has-text('Payment')",
            "button:has-text('Payment')",
        ],
        "create_quote_link": [
            "a:has-text('Create Quote')",
            "a.create-quote-link",
            "a[href*='quote' i]:has-text('Create Quote')",
            "button:has-text('Create Quote')",
        ],
    },
    "quote_modal": {
        "modal_dialog": [
            "div[role='dialog']:has-text('Create Quote')",
            "div.modal.show:has-text('Quote')",
            ".modal.show",
            "div[role='dialog']:visible",
        ],
        "close_button": [
            "div[role='dialog'] button:has-text('Close')",
            ".modal.show button.close",
            ".modal.show button:has-text('Close')",
            "div[role='dialog'] button[aria-label='Close']",
            ".modal.show [aria-label='Close']",
        ],
        "submit_quote_button": [
            "button:has-text('Submit Quote')",
            "a:has-text('Submit Quote')",
            "button.submit-quote",
            "form button[type='submit']:has-text('Submit')",
        ],
        "confirmation_heading": [
            "h1:has-text('Quote Confirmation')",
            "h1.page-title:has-text('Quote Confirmation')",
            ":text-matches('Quote Confirmation', 'i')",
        ],
    },
    "account": {
        "my_account_link": [
            "a:has-text('My Account')",
            "header a:has-text('My Account')",
            "a.user-account-link",
            "a[href*='account' i]:has-text('My Account')",
        ],
        "my_quotes_and_orders_link": [
            "a:has-text('My Quotes and Orders')",
            "a:has-text('My Quotes & Orders')",
            "a[href*='quotes-orders' i]",
            "a[href*='quotesandorders' i]",
            "a[href*='quotes' i]",
        ],
        "my_quotes_heading": [
            "h1:has-text('My Quotes and Orders')",
            "h1:has-text('My Quotes & Orders')",
            "h1.page-title:has-text('Quotes')",
        ],
        "delete_quote_link": [
            "a:has-text('Delete')",
            "a.delete-quote",
            "a.delete-link",
            "button:has-text('Delete')",
            "a[data-action*='delete' i]",
        ],
        "delete_popup": [
            "div[role='dialog']:has-text('Delete')",
            "div.modal.show:has-text('Delete')",
        ],
        "delete_popup_yes": [
            "div[role='dialog'] a:has-text('Yes')",
            "div[role='dialog'] button:has-text('Yes')",
            ".modal.show a:has-text('Yes')",
            ".modal.show button:has-text('Yes')",
        ],
        "no_quotes_text": [
            ":text-matches('You have no\\\\s+quotes', 'i')",
            ":text-matches('no quotes', 'i')",
            ".no-quotes-message",
        ],
    },
    "cart": {
        "subtotal_value": [
            ".cart-totals .sub-total .grand-total-sum",
            ".cart-totals .subtotal .value",
            ".cart-summary .sub-total .value",
            ".totals .sub-total .value",
            ".summary-row.subtotal .value",
            "[class*='subtotal'] [class*='value']",
        ],
        "added_to_cart_success": [
            "#addedProductwrapper",
            "div.toast-success",
            "div.alert-success:has-text('added to cart')",
            ".add-to-cart-messages.success",
            ":text-matches('product added to cart', 'i')",
            "text=/added to (your )?cart/i",
        ],
        "cart_line_item": [
            "div.product-info[class*='uuid-']",
            "div.product-info",
            "div.line-item",
            "div.cart-item",
            "div[class*='line-item']",
            "div[class*='cart-item']:not(.cart-items-qty)",
            "li[class*='line-item']",
            "div[data-itemid]",
        ],
        "cart_line_item_name": [
            "div.product-info .line-item-name",
            "div.line-item .line-item-name",
            "div.cart-item .line-item-name",
            "[class*='line-item'] [class*='name']",
            "[class*='cart-item'] [class*='name']",
        ],
        "cart_line_item_price": [
            "div.product-info .line-item-total-price-amount",
            "div.line-item .line-item-total-price-amount",
            "div.line-item .price .sales .value",
            "div.line-item .price",
            "[class*='line-item'] [class*='price']",
            "[class*='cart-item'] [class*='price']",
        ],
        "cart_heading": [
            "h1.page-title:has-text('Your Cart')",
            "h1:has-text('Your Cart')",
            "h1:has-text('Shopping Cart')",
            "h1:has-text('Cart')",
        ],
        "quantity_increase": [
            "div.product-info button.quantity-form-increase",
            "div.product-info button[aria-label*='Increase' i]",
            "div.product-info button.quantity-button:has-text('+')",
            "div.product-info button.btn-plus",
            "button.quantity-form-increase",
            "button.quantity-button:has-text('+')",
            "button[aria-label*='Increase' i]",
            "button.btn-plus",
            "button.plus",
            "button:has-text('+')",
        ],
        "clear_my_order": [
            "button:has-text('Clear My Order')",
            "a:has-text('Clear My Order')",
            "button.clear-cart",
            "button[data-action*='clear' i]",
        ],
        "clear_popup": [
            "#clearCartModal.show",
            "#clearCartModal[style*='display: block']",
            "#clearCartConfirmationModal.show",
            "#clearCartConfirmationModal[style*='display: block']",
            "div[role='dialog']:has-text('Clear your Cart')",
            "div.modal.show:has-text('Clear your Cart')",
            ".modal:has-text('Clear your Cart')",
            "div[role='dialog']:has-text('Clear Your Cart')",
            ".modal.show:has-text('Clear')",
        ],
        "popup_yes": [
            "#clearCartModal a:has-text('Yes')",
            "#clearCartModal a.btn-secondary",
            "#clearCartModal a[href*='Cart-ClearBasket']",
            "a[data-element-linkname='Clear Your Cart | Yes']",
            "div.modal.show a:has-text('Yes')",
            "div.modal.show .btn:has-text('Yes')",
            "div[role='dialog'] a:has-text('Yes')",
            "div[role='dialog'] button:has-text('Yes')",
            "div.modal.show button:has-text('Yes')",
            ".modal a:has-text('Yes')",
            ".modal button:has-text('Yes')",
            "button.btn-confirm-clear",
            "button[data-action='confirm-clear']",
        ],
        "empty_cart_message": [
            ":text-matches('cart is empty', 'i')",
            ":text-matches('your cart is empty', 'i')",
            ":text-matches('no items in (your )?cart', 'i')",
            ".empty-cart-message",
            ".cart-empty",
        ],
    },
}
