"""Built-in fallback selector map used when mcp-selectors/locators.json is missing/empty.

base_page.BasePage prefers locators.json but falls back to LOCATORS here so the
framework remains runnable even if the JSON file is reset between sessions.
"""

from __future__ import annotations

LOCATORS: dict[str, dict[str, list[str]]] = {
    "common": {
        "cookie_accept": [
            "button#onetrust-accept-btn-handler",
            "button[title='Accept All Cookies']",
            "button[aria-label*='Accept All' i]",
            "button:has-text('Accept All Cookies')",
            "button:has-text('Accept All')",
            "button:has-text('Allow All')",
        ],
    },
    "home": {
        "sign_in_link": [
            "a.signModal[aria-label='Login to your account']",
            "header a.signModal",
            "a.signModal:has-text('Sign In')",
            "a.signModal:has-text('Educator Sign In')",
            "header a:has-text('Educator Sign In')",
            "header a:has-text('Sign In')",
            "a[role='button']:has-text('Sign In')",
            "a:has-text('Sign In')",
            "button:has-text('Sign In')",
        ],
        "search_textbox": [
            "header input[name='q'].search-field",
            "input[name='q'].search-field",
            "input[placeholder*='Search by Keyword' i]",
            "input[type='search']",
            "input[name='q']",
        ],
        "search_submit_button": [
            "header form[role='search'] svg[name='search-button']",
            "form[role='search'] svg[name='search-button']",
            "header button[aria-label='Search']",
            "header form[role='search'] button[type='submit']",
            "form[role='search'] button[type='submit']",
            "header button:has-text('Search')",
            "button[type='submit']:has-text('Search')",
        ],
        "cart_link": [
            "header a.minicart-link",
            "a.minicart-link",
            "header a[href*='/en/cart']",
            "a[href$='/en/cart']",
            "a[aria-label*='Cart' i]",
            "a:has-text('Cart')",
        ],
        "logged_in_account": [
            "a.user-logout",
            "span.user-firstname:has-text('Welcome,')",
            ".user-firstname",
            "header :text-matches('Welcome,', 'i')",
            "button:has-text('My Account')",
            "header button:has-text('Welcome')",
            "text=My Account",
            "text=Welcome,",
        ],
    },
    "signin_modal": {
        "dialog": [
            "form#loginForm",
            "#loginForm",
            "div[role='dialog']:has-text('Account Sign In')",
            "div[role='dialog']:has-text('Sign In')",
            ".modal:has-text('Sign In')",
        ],
        "email_input": [
            "form#loginForm input.lf_email",
            "form#loginForm input[name='loginEmail']",
            "form#loginForm input#login-form-email",
            "#loginForm input.lf_email",
            "#loginForm input[name='loginEmail']",
            "#loginForm input[type='email']",
            "input.lf_email:visible",
            "input#login-form-email",
            "input[name='loginEmail']:visible",
            "input[type='email']:visible",
        ],
        "password_input": [
            "form#loginForm input.lf_password",
            "form#loginForm input[name='loginPassword']",
            "form#loginForm input#login-form-password",
            "#loginForm input.lf_password",
            "#loginForm input[name='loginPassword']",
            "#loginForm input[type='password']",
            "input.lf_password:visible",
            "input#login-form-password",
            "input[name='loginPassword']:visible",
            "input[type='password']:visible",
        ],
        "submit_button": [
            "form#loginForm button.lf_submit",
            "form#loginForm button[type='submit']",
            "form#loginForm button:has-text('Sign In')",
            "form#loginForm button:has-text('Login')",
            "#loginForm button.lf_submit",
            "#loginForm button[type='submit']",
            "#loginForm button:has-text('Sign In')",
            "div[role='dialog'] button:has-text('Sign In')",
            "div[role='dialog'] button[type='submit']",
            ".modal button:has-text('Sign In')",
        ],
        "error_message": [
            "#loginForm .alert.alert-danger",
            "#loginForm .alert-danger",
            "#loginForm .login-form-error",
            "#loginForm .form-error",
            "#loginForm .error-message",
            "#loginForm .invalid-feedback",
            "#loginForm small.text-danger",
            ".modal.show .alert-danger",
            ".modal.show .text-danger",
            ".modal.show :text-matches('Sorry, we cannot find', 'i')",
            ":text-matches('Sorry, we cannot find an account', 'i')",
        ],
    },
    "search_results": {
        "product_tile": [
            "div.product-tile",
            "div[class*='product-tile']",
            "div[data-itemid]",
            "div.grid-tile",
            "div[class*='grid-tile']",
        ],
        "first_tile_price": [
            "div.product-tile .line-item-total-price-amount",
            "div.product-tile .price-value",
            "div.product-tile .product-pricing .price-value",
            "div.product-tile .product-sales-price .price-value",
            ".price-value",
        ],
        "first_tile_add_to_cart": [
            "button.add-to-cart:not(.donateToClass):not(.d-none)",
            "button.add-to-cart:not(.donateToClass)",
            "button.add-to-cart",
            "button:has-text('Add to Cart')",
        ],
        "added_confirmation": [
            "#addedProductwrapper",
            "text=/added to (your )?cart/i",
            "div[role='dialog']:has-text('added to')",
            ".add-to-cart-messages",
            "div.toast:has-text('added')",
        ],
    },
    "cart": {
        "added_to_cart_success": [
            "#addedProductwrapper",
            "div.toast-success",
            "div.alert-success:has-text('added to cart')",
            ".add-to-cart-messages.success",
            ":text-matches('product added to cart', 'i')",
            "text=/added to (your )?cart/i",
        ],
        "cart_line_item": [
            "div.product-info[class*='uuid-']",
            "div.product-info",
            "div.line-item",
            "div.cart-item",
            "div[class*='line-item']",
            "div[class*='cart-item']:not(.cart-items-qty)",
            "li[class*='line-item']",
            "div[data-itemid]",
        ],
        "cart_heading": [
            "h1.page-title:has-text('Your Cart')",
            "h1:has-text('Your Cart')",
            "h1:has-text('Shopping Cart')",
            "h1:has-text('Cart')",
        ],
        "quantity_increase": [
            "div.product-info button.quantity-form-increase",
            "div.product-info button[aria-label*='Increase' i]",
            "div.product-info button.quantity-button:has-text('+')",
            "div.product-info button.btn-plus",
            "button.quantity-form-increase",
            "button.quantity-button:has-text('+')",
            "button[aria-label*='Increase' i]",
            "button.btn-plus",
            "button.plus",
            "button:has-text('+')",
        ],
        "clear_my_order": [
            "button:has-text('Clear My Order')",
            "a:has-text('Clear My Order')",
            "button.clear-cart",
            "button[data-action*='clear' i]",
        ],
        "clear_popup": [
            "#clearCartModal.show",
            "#clearCartModal[style*='display: block']",
            "#clearCartConfirmationModal.show",
            "#clearCartConfirmationModal[style*='display: block']",
            "div[role='dialog']:has-text('Clear your Cart')",
            "div.modal.show:has-text('Clear your Cart')",
            ".modal:has-text('Clear your Cart')",
            "div[role='dialog']:has-text('Clear Your Cart')",
            ".modal.show:has-text('Clear')",
        ],
        "popup_yes": [
            "#clearCartModal a:has-text('Yes')",
            "#clearCartModal a.btn-secondary",
            "#clearCartModal a[href*='Cart-ClearBasket']",
            "a[data-element-linkname='Clear Your Cart | Yes']",
            "div.modal.show a:has-text('Yes')",
            "div.modal.show .btn:has-text('Yes')",
            "div[role='dialog'] a:has-text('Yes')",
            "div[role='dialog'] button:has-text('Yes')",
            "div.modal.show button:has-text('Yes')",
            ".modal a:has-text('Yes')",
            ".modal button:has-text('Yes')",
            "button.btn-confirm-clear",
            "button[data-action='confirm-clear']",
        ],
        "empty_cart_message": [
            ":text-matches('cart is empty', 'i')",
            ":text-matches('your cart is empty', 'i')",
            ":text-matches('no items in (your )?cart', 'i')",
            ".empty-cart-message",
            ".cart-empty",
        ],
    },
}
